#!/usr/bin/env python3
"""Embed files into fit.elf (and fit_native) as byte arrays.

The guest cannot open files (Gate 0F: EBADF), so the JSON rules the solver
validates its setup against ship inside the binary. Modelled on
kernels/embed_spv.py: one static array per file plus a name -> bytes table.
Each array is NUL-terminated (not counted in the size) so text can be parsed
in place.

The generated .cpp defines
    const char *fit::embedded_file(const char *name, size_t *size);
    extern "C" const char *polysolve_embedded_spec(const char *name);
the second being what vendor/cloth-fit-patches/polysolve-embedded-specs.patch
declares under POLYSOLVE_EMBEDDED_SPECS.

    python tools/fit/embed_files.py out.cpp guest/fit/specs/*.json
Names are the file basenames.
"""

import pathlib
import sys


def ident(i):
    return "k_file_%d" % i


def emit(out_path, paths):
    paths = [pathlib.Path(p) for p in paths]
    names = [p.name for p in paths]
    if len(set(names)) != len(names):
        raise SystemExit("duplicate basenames: %s" % names)
    lines = [
        "// Generated by tools/fit/embed_files.py. Do not edit; regenerate.",
        "#include <cstddef>",
        "",
        "namespace {",
        "",
    ]
    total = 0
    for i, p in enumerate(paths):
        data = p.read_bytes()
        total += len(data)
        lines.append("// %s" % p.as_posix())
        lines.append("const char %s[%d] = {" % (ident(i), len(data) + 1))
        for k in range(0, len(data), 24):
            chunk = data[k:k + 24]
            lines.append("\t" + ",".join("%d" % (b if b < 128 else b - 256) for b in chunk) + ",")
        lines.append("\t0};")
        lines.append("")
    lines.append("struct Entry {")
    lines.append("\tconst char *name;")
    lines.append("\tconst char *bytes;")
    lines.append("\tsize_t size;")
    lines.append("};")
    lines.append("")
    lines.append("const Entry kEntries[] = {")
    for i, n in enumerate(names):
        lines.append('\t{"%s", %s, sizeof(%s) - 1},' % (n, ident(i), ident(i)))
    lines.append("};")
    lines.append("")
    lines.append("bool same(const char *a, const char *b) {")
    lines.append("\twhile (*a && *a == *b) {")
    lines.append("\t\t++a;")
    lines.append("\t\t++b;")
    lines.append("\t}")
    lines.append("\treturn *a == 0 && *b == 0;")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace")
    lines.append("")
    lines.append("namespace fit {")
    lines.append("const char *embedded_file(const char *name, size_t *size) {")
    lines.append("\tfor (const Entry &e : kEntries)")
    lines.append("\t\tif (same(e.name, name)) {")
    lines.append("\t\t\tif (size)")
    lines.append("\t\t\t\t*size = e.size;")
    lines.append("\t\t\treturn e.bytes;")
    lines.append("\t\t}")
    lines.append("\treturn nullptr;")
    lines.append("}")
    lines.append("} // namespace fit")
    lines.append("")
    lines.append('extern "C" const char *polysolve_embedded_spec(const char *name) {')
    lines.append("\treturn fit::embedded_file(name, nullptr);")
    lines.append("}")
    lines.append("")
    out = pathlib.Path(out_path)
    text = "\n".join(lines)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8", newline="\n")
    print("embedded %d files, %d bytes -> %s" % (len(paths), total, out_path))


if __name__ == "__main__":
    if len(sys.argv) < 3:
        raise SystemExit(__doc__)
    emit(sys.argv[1], sys.argv[2:])
